spring:
  datasource:
    password: john1234
    url: jdbc:mysql://localhost:3306/user_management
    username: john

  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web: 
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always
    env:
      show-values: always
        
info:
  app:
    name: Spring Boot  Restful Web Services
    description: Spring Boot Restful Web Services Demo
    version: 1.0.0